# This workflow will build a package using Maven and then publish it to Maven Central when a release is created

name: Maven Publish to Central

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Import GPG key
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --dearmor > private.gpg
        gpg --import --batch --yes private.gpg
        rm private.gpg

    - name: Create Maven settings.xml
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << EOF
        <settings>
          <servers>
            <server>
              <id>ossrh</id>
              <username>${{ secrets.OSSRH_USERNAME }}</username>
              <password>${{ secrets.OSSRH_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Verify settings.xml (debug)
      run: |
        echo "Settings file exists: $(ls -la ~/.m2/settings.xml)"
        echo "Settings file content (credentials masked):"
        sed 's/<username>.*<\/username>/<username>[MASKED]<\/username>/g; s/<password>.*<\/password>/<password>[MASKED]<\/password>/g' ~/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to Maven Central
      run: mvn --no-transfer-progress --batch-mode deploy
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
